FROM kris310/pyterrier-base:py3.10
 
# Set work dir
WORKDIR /app

# Copy list of dependencies
COPY ./requirements.txt /app

# Install all dependecies
RUN pip3 install --no-cache-dir --upgrade -r requirements.txt

# Copy the project
COPY . /app

# Run the server
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080"]