FROM python:3.10
 
# Update the package lists and install necessary packages
RUN apt update && apt-get update

# Install pcre to resolve pyautocorpus issue
RUN apt install libpcre3-dev -y

# Install JDK
RUN apt install default-jdk -y

RUN pip3 install --no-cache-dir --upgrade python-terrier
